name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    paths-ignore:
      - ".github/**"
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDTYPE: Release
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"  

      - name: Build Plugins SDK
        run: make build-release

      - name: Publish to MavenCentral
        run: make publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
